name: truck_monitor
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.1
  remixicon: ^1.0.0
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.2
  rflutter_alert: ^2.0.7
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.11
  flutter_chat_bubble: ^2.0.2
  http: ^1.0.0
  recase: ^4.1.0
  email_validator: ^2.1.17
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  maps_launcher: ^2.2.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    image: assets/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
