# Generated by Django 4.1.5 on 2023-06-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=80, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("mobile", models.CharField(max_length=13, unique=True)),
                ("role", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="easy_load.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("mobile", models.CharField(max_length=13, unique=True)),
                ("licence_no", models.CharField(max_length=20, unique=True)),
                ("role", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="easy_load.log"
                    ),
                ),
            ],
        ),
    ]
