# Generated by Django 4.1.5 on 2023-06-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_load", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="location",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="log",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
