# Generated by Django 4.1.5 on 2023-06-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0002_driver_location_user_location_alter_log_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="vehicle_status",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_name", models.CharField(max_length=100, unique=True)),
                ("trucknoController", models.CharField(max_length=80, unique=True)),
                ("timeController", models.CharField(max_length=100, unique=True)),
                ("role", models.CharField(max_length=10)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.driver",
                    ),
                ),
            ],
        ),
    ]
