# Generated by Django 4.1.5 on 2023-06-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_load", "0003_driver_vehicle_status_truck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_status",
            field=models.CharField(max_length=50),
        ),
    ]
