# Generated by Django 4.1.5 on 2023-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0004_alter_driver_location_alter_driver_vehicle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="transport_from",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="transport_to",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
