# Generated by Django 4.1.5 on 2023-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_load", "0006_drivertruck_delete_truck"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivertruck",
            name="driver_name",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
