# Generated by Django 4.1.5 on 2023-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0008_alter_drivertruck_truckfrom_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
