# Generated by Django 4.1.5 on 2023-06-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0009_load_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="TruckBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("truck_name", models.CharField(max_length=100)),
                ("driver_name", models.CharField(max_length=100)),
                ("load_quantity", models.CharField(max_length=100)),
                ("starting", models.CharField(max_length=80)),
                ("ending", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="easy_load.load"
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.drivertruck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="easy_load.user"
                    ),
                ),
            ],
        ),
    ]
