# Generated by Django 4.1.5 on 2023-06-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("easy_load", "0010_truckbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckbooking",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="easy_load.driver",
            ),
            preserve_default=False,
        ),
    ]
