# Generated by Django 4.1.5 on 2023-07-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0011_truckbooking_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivertruck",
            name="driver_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="drivertruck",
            name="truck_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="drivertruck",
            name="trucknumber",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(max_length=50),
        ),
    ]
