# Generated by Django 4.1.5 on 2023-07-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0012_alter_drivertruck_driver_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat_Replay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat", models.CharField(max_length=500)),
                ("date", models.CharField(max_length=100)),
                ("replay", models.CharField(default="No Replay", max_length=500)),
                ("chat_status", models.CharField(max_length=10)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.user",
                    ),
                ),
            ],
        ),
    ]
