# Generated by Django 4.1.5 on 2023-07-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("easy_load", "0013_chat_replay"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_replay",
            name="drivername",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat_replay",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat_replay",
            name="replay",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.CreateModel(
            name="load_requset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("drivername", models.CharField(max_length=100)),
                ("load_from", models.CharField(max_length=80)),
                ("load_to", models.CharField(max_length=100)),
                ("load_quantity", models.CharField(max_length=100)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=100)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.driver",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.load",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easy_load.user",
                    ),
                ),
            ],
        ),
    ]
