# Generated by Django 4.1.5 on 2023-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easy_load", "0015_alter_log_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckbooking",
            name="amount",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="truckbooking",
            name="payment_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
